# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: hello_world
  username: sampleuser
  password: password
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: hello_world
  username: sampleuser
  password: password
  host: localhost
  port: 3306
  pool: 256
  timeout: 5000
